function init(self)
	msg.post(".", "start_main_menu")
	self.state = "MAIN_MENU"
end

function on_message(self, message_id, message, sender)
	if message_id == hash("start_level1") then
		msg.post("#level1", "load")
		msg.post("#main_menu", "disable")
	elseif message_id == hash("proxy_loaded") then
		if sender == msg.url("#level1") then
			msg.post(sender, "enable")
			self.state = "GAME1_RUNNING"
		end
	end
end
		