function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		local button = gui.get_node("startGame")
		local text = gui.get_node("text")
		if(gui.pick_node(button, action.x, action.y)) then
			gui.set_text(text, "HELLO")
			msg.post("/go#level1", "load")
			msg.post("#main_menu", "disable")
		else
			gui.set_text(text, "START GAME")
		end
	end
end
		